version: '2'

services:
  web:
    build: .
    command: sh -c 'sleep 5 & python /code/manage.py runserver 0.0.0.0:8000' 
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
    networks:
      - mynetwork
    restart: "on-failure:10"
    environment:
      - POSTGRES_HOST=db
  db:
    image: postgres:13
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

volumes:
  postgres_data:
  