# Generated by Django 4.1.7 on 2023-03-08 13:46

from django.db import migrations
from accounts.models import Role


def create_roles(apps, schema_editor):
    basic_role = Role.objects.create(
        name="Basic", thumbnail_size=200, allow_original=False, allow_expiring=False
    )
    premium_role = Role.objects.create(
        name="Premium", thumbnail_size=400, allow_original=True, allow_expiring=False
    )
    enterprise_role = Role.objects.create(
        name="Enterprise", thumbnail_size=400, allow_original=True, allow_expiring=True
    )
    custom_role = Role.objects.create(
        name="firstcustomrole",
        thumbnail_size=600,
        allow_original=False,
        allow_expiring=False,
    )
    basic_role.save()
    premium_role.save()
    enterprise_role.save()
    custom_role.save()


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        # migrations.RunPython(create_roles),
    ]
