# Generated by Django 4.1.7 on 2023-03-08 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_customuser_role"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="usernamee",
        ),
    ]
