# Generated by Django 4.1.7 on 2023-03-10 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0003_thumbnail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="thumbnail",
            name="thumbnail_file",
            field=models.ImageField(upload_to="thumbnails/"),
        ),
    ]
