# Generated by Django 4.1.7 on 2023-03-15 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0004_alter_thumbnail_thumbnail_file"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExpiringImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("expire_time", models.DateTimeField()),
                ("url", models.URLField(blank=True, null=True)),
                (
                    "image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="images.image",
                    ),
                ),
            ],
        ),
    ]
